name: "Deploy to Netlify"

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to Netlify"
    steps:
      - uses: wei/curl@v1.1.1
        with:
          args: -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
